const card = 'bg-slate-800/50 border border-slate-700 rounded-3xl p-8 relative overflow-hidden group hover:border-cyan-400 hover:shadow-[0_0_40px_rgba(34,211,238,0.15)] hover:-translate-y-2 transition-all duration-500';
const action = 'w-full rounded-full bg-slate-700 text-slate-300 py-4 mt-8 font-bold group-hover:bg-gradient-to-r group-hover:from-cyan-500 group-hover:to-blue-600 group-hover:text-white group-hover:shadow-lg transition-all duration-300';

export function renderAluno(conteudos = [], mentores = [], usuario = null) {
  return `<section class="space-y-12 text-slate-100">${usuario ? `<div class="rounded-3xl border border-slate-700 bg-slate-800/40 p-6"><p class="text-sm font-bold uppercase tracking-widest text-cyan-400">Painel do Aluno</p><h1 class="mt-2 text-3xl font-bold text-white">Olá, ${usuario.nome}</h1><p class="mt-2 text-slate-400">Filtro ativo: ${usuario.interesse || 'Todas as áreas'}</p></div>` : ''}<div><h1 class="bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Conteúdos Recomendados</h1><div class="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3">${conteudos.length ? conteudos.map((item) => `<article class="${card}"><span class="rounded-full border border-cyan-400/40 bg-cyan-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-cyan-300">${item.tipo}</span><h2 class="mt-5 text-white font-bold text-2xl group-hover:text-cyan-400 transition-colors">${item.titulo}</h2><p class="mt-3 text-slate-400">Por ${item.autor || 'Professor HACD-Hub'} · ${item.area || ''}</p><button data-page="conteudo" data-id="${item.id}" class="${action}">Acessar Trilha</button></article>`).join('') : '<p class="text-slate-400 md:col-span-3">Ainda não há conteúdos para esta área.</p>'}</div></div><div><h1 class="bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Mentores Disponíveis</h1><div class="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3">${mentores.length ? mentores.map((professor) => `<article class="${card}"><h2 class="text-white font-bold text-2xl group-hover:text-cyan-400 transition-colors">${professor.nome}</h2><p class="mt-3 text-slate-300">${professor.especialidade}</p><p class="mt-2 text-slate-400">Disponibilidade: ${professor.disponibilidade || 'A combinar'}</p><button data-page="solicitar-mentoria" data-id="${professor.id}" data-email="${professor.email}" data-nome="${professor.nome}" data-especialidade="${professor.especialidade}" class="${action}">Solicitar Mentoria</button></article>`).join('') : '<p class="text-slate-400 md:col-span-3">Nenhum mentor encontrado para este filtro.</p>'}</div></div></section>`;
}

export function renderProfessor(alunos = [], usuario = null, artigos = []) {
  return `<section class="space-y-12 text-slate-100">${usuario ? `<div class="rounded-3xl border border-slate-700 bg-slate-800/40 p-6"><p class="text-sm font-bold uppercase tracking-widest text-emerald-400">Painel do Professor</p><h1 class="mt-2 text-3xl font-bold text-white">Olá, ${usuario.nome}</h1><p class="mt-2 text-slate-400">Especialidade: ${usuario.especialidade || 'A definir'}</p></div>` : ''}<div class="flex flex-wrap gap-4"><button data-page="publicar-artigo" class="rounded-full bg-emerald-600 px-8 py-3 font-bold text-white shadow-lg transition-transform hover:scale-105 hover:bg-emerald-500">Escrever Artigo</button></div><div><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-widest text-emerald-400">Conteúdo publicado</p><h1 class="mt-2 bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Meus Artigos</h1></div></div><div class="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3">${artigos.length ? artigos.map((item) => `<article class="${card}"><span class="text-xs font-bold uppercase tracking-widest text-cyan-400">${item.area || 'Artigo'}</span><h2 class="mt-4 text-white font-bold text-2xl group-hover:text-cyan-400 transition-colors">${item.titulo}</h2><button data-page="conteudo" data-id="${item.id}" class="${action}">Ver Artigo</button></article>`).join('') : '<p class="text-slate-400 md:col-span-3">Você ainda não publicou artigos.</p>'}</div></div><div><h1 class="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Alunos aguardando mentoria</h1><div class="mt-6 grid grid-cols-1 gap-6 md:grid-cols-3">${alunos.length ? alunos.map((aluno) => `<article class="${card}"><h2 class="text-white font-bold text-2xl group-hover:text-cyan-400 transition-colors">${aluno.nome}</h2><p class="mt-3 text-slate-300">Nível: ${aluno.nivel || 'A definir'}</p><p class="mt-2 text-slate-300">Interesse: ${aluno.interesse}</p><button data-page="oferecer-mentoria" data-id="${aluno.id}" data-email="${aluno.email}" data-nome="${aluno.nome}" data-interesse="${aluno.interesse}" class="${action}">Oferecer Mentoria</button></article>`).join('') : '<p class="text-slate-400 md:col-span-3">Nenhum aluno encontrado para este filtro.</p>'}</div></div></section>`;
}

export function renderArtigo(id, conteudos = []) {
  const item = conteudos.find((conteudo) => String(conteudo.id) === String(id));
  if (!item) return '<section class="rounded-3xl border border-slate-700 bg-slate-800/50 p-8 text-slate-300">Conteúdo não encontrado.</section>';
  return `<article class="mx-auto max-w-3xl rounded-[2rem] border border-slate-700 bg-slate-900/80 p-10 shadow-[0_0_50px_rgba(0,0,0,0.4)]"><button data-page="aluno" class="mb-8 text-sm font-bold text-cyan-400 transition hover:text-cyan-300">Voltar para trilhas</button><span class="rounded-full border border-cyan-400/40 bg-cyan-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-cyan-300">${item.area}</span><h1 class="mt-5 text-4xl font-black leading-tight text-white">${item.titulo}</h1><p class="mt-3 text-slate-400">Por ${item.autor || 'Professor HACD-Hub'}</p><div class="mt-8 space-y-5 text-lg leading-8 text-slate-300">${(item.corpo || '').split('\n').map((paragrafo) => `<p>${paragrafo}</p>`).join('')}</div></article>`;
}

export function renderPublicarConteudo(usuario) {
  return `<div class="flex justify-center"><section class="w-full max-w-xl rounded-[2rem] border border-slate-700 bg-slate-900/80 p-10 shadow-[0_0_50px_rgba(0,0,0,0.4)] backdrop-blur-xl"><h1 class="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Escrever Artigo</h1><form id="form-conteudo" class="mt-8 space-y-5"><label class="block text-sm font-semibold text-slate-200">Título<input id="titulo-conteudo" required class="mt-2 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white outline-none transition-all focus:border-transparent focus:ring-2 focus:ring-cyan-500"></label><label class="block text-sm font-semibold text-slate-200">Área<input id="area-conteudo" required value="${usuario?.especialidade || ''}" class="mt-2 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white outline-none transition-all focus:border-transparent focus:ring-2 focus:ring-cyan-500"></label><label class="block text-sm font-semibold text-slate-200">Artigo<textarea id="corpo-conteudo" required rows="8" class="mt-2 w-full resize-none rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white outline-none transition-all focus:border-transparent focus:ring-2 focus:ring-cyan-500"></textarea></label><button type="submit" class="w-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 py-4 font-bold text-white transition-all hover:scale-[1.02] hover:opacity-90">Publicar artigo</button></form></section></div>`;
}
