const inputStyle = 'mt-2 w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white outline-none transition-all placeholder:text-slate-500 focus:border-transparent focus:ring-2 focus:ring-cyan-500';
const cardStyle = 'w-full max-w-xl rounded-[2rem] border border-slate-700 bg-slate-900/80 p-10 shadow-[0_0_50px_rgba(0,0,0,0.4)] backdrop-blur-xl';

export function renderCadastro(tipoPre = '', interessePre = '') {
  return `<div class="flex justify-center"><section class="${cardStyle}"><h1 class="bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Junte-se ao Hub</h1><form id="form-cadastro" class="mt-8 space-y-5"><label class="block text-sm font-semibold text-slate-200">Nome<input id="nome" type="text" required class="${inputStyle}" placeholder="Seu nome"></label><label class="block text-sm font-semibold text-slate-200">Email<input id="email" type="email" required class="${inputStyle}" placeholder="voce@email.com"></label><label class="block text-sm font-semibold text-slate-200">Senha<input id="senha" type="password" required class="${inputStyle}" placeholder="Crie uma senha"></label><label class="block text-sm font-semibold text-slate-200">Interesse/Especialidade<input id="interesse" type="text" required value="${interessePre}" class="${inputStyle}" placeholder="Programação, Design..."></label><label class="block text-sm font-semibold text-slate-200">Tipo de usuário<select id="tipo-usuario" class="${inputStyle}"><option value="aluno" ${tipoPre === 'aluno' ? 'selected' : ''}>Aluno</option><option value="professor" ${tipoPre === 'professor' ? 'selected' : ''}>Professor</option></select></label><button type="submit" class="mt-6 w-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 py-4 font-bold text-white transition-all hover:scale-[1.02] hover:opacity-90">Enviar cadastro</button></form></section></div>`;
}

export function renderLogin() {
  return `<div class="flex justify-center"><section class="${cardStyle}"><h1 class="bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Entrar no HACD-Hub</h1><form id="form-login" class="mt-8 space-y-5"><label class="block text-sm font-semibold text-slate-200">Email<input id="login-email" type="email" required class="${inputStyle}" placeholder="voce@email.com"></label><label class="block text-sm font-semibold text-slate-200">Senha<input id="senha" type="password" required class="${inputStyle}" placeholder="Sua senha"></label><button type="submit" class="mt-6 w-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 py-4 font-bold text-white transition-all hover:scale-[1.02] hover:opacity-90">Entrar na Plataforma</button></form><button id="link-recuperar-senha" class="mt-5 w-full text-center text-sm font-semibold text-cyan-400 transition hover:text-cyan-300">Esqueci minha senha</button><button id="link-cadastro" class="mt-6 w-full text-center text-sm font-semibold text-slate-400 transition hover:text-cyan-400">Ainda não tem conta? Cadastre-se</button></section></div>`;
}

export function renderRecuperarSenha() {
  return `<div class="flex justify-center"><section class="${cardStyle}"><h1 class="bg-gradient-to-r from-blue-500 to-cyan-400 bg-clip-text text-3xl font-bold text-transparent">Recuperar senha</h1><p class="mt-4 text-slate-400">Informe seu email para receber instruções de recuperação.</p><form id="form-recuperar-senha" class="mt-8 space-y-5"><label class="block text-sm font-semibold text-slate-200">Email<input id="recuperar-email" type="email" required class="${inputStyle}" placeholder="voce@email.com"></label><button type="submit" class="mt-6 w-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 py-4 font-bold text-white transition-all hover:scale-[1.02] hover:opacity-90">Enviar instruções</button></form></section></div>`;
}
