export function renderHome() {
  return `
    <section class="min-h-screen pt-10">
      <div class="grid min-h-screen items-center gap-12 lg:grid-cols-2">
        <div>
          <p class="mb-5 inline-flex rounded-full border border-slate-700 bg-slate-800/50 px-4 py-2 text-sm font-semibold text-slate-300">Educação comunitária, direta e acessível</p>
          <h1 class="max-w-3xl text-5xl font-extrabold leading-tight text-white md:text-7xl">Aprenda com pessoas da sua comunidade.</h1>
          <p class="mt-6 max-w-2xl text-xl leading-8 text-slate-400">O HACD-Hub aproxima alunos e professores em uma experiência simples: encontre uma área, leia conteúdos, peça mentoria e avance com apoio real.</p>
          <div class="mt-10 flex flex-wrap gap-4">
            <button data-page="aluno" class="rounded-full bg-white px-8 py-4 text-lg font-bold text-slate-950 transition hover:-translate-y-1 hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:ring-offset-4 focus:ring-offset-slate-900">Explorar trilhas</button>
            <button data-page="cadastro" data-tipo="professor" class="rounded-full border border-slate-700 px-8 py-4 text-lg font-bold text-slate-200 transition hover:-translate-y-1 hover:border-cyan-400 hover:text-white">Quero ensinar</button>
          </div>
        </div>
        <div class="relative flex min-h-[620px] items-center justify-center [perspective:1200px]">
          <div class="absolute h-[520px] w-[330px] rounded-full bg-cyan-400/10 blur-3xl"></div>
          <div data-parallax data-depth="-8" class="relative z-10 transition-transform duration-200">
            <div class="phone-float relative h-[580px] w-[280px] rotate-[-8deg] overflow-hidden rounded-[3rem] border-[12px] border-slate-800 bg-slate-900 shadow-[0_0_50px_rgba(56,189,248,0.3)] transition-transform duration-700 ease-out hover:rotate-0">
              <div class="absolute left-1/2 top-0 z-20 h-6 w-32 -translate-x-1/2 rounded-b-2xl bg-slate-800"></div>
              <div data-parallax data-depth="5" class="relative flex h-full w-full flex-col overflow-hidden rounded-[2rem] border border-slate-700 bg-gradient-to-b from-slate-800 via-slate-900 to-slate-950 p-6 pt-12 transition-transform duration-200">
                <div class="flex items-center justify-between text-xs text-slate-500"><span>09:41</span><span class="flex gap-1"><i class="h-2 w-2 rounded-full bg-emerald-400"></i><i class="h-2 w-2 rounded-full bg-cyan-400"></i></span></div>
                <div class="mt-10"><p class="text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">Sua próxima ideia</p><h2 class="mt-3 text-3xl font-black leading-tight text-white">Aprender fica melhor em conjunto.</h2></div>
                <div class="mt-8 rounded-3xl border border-slate-700 bg-slate-950/70 p-4 shadow-inner shadow-cyan-950/30"><div class="mb-5 flex items-center justify-between"><span class="text-sm font-semibold text-slate-300">Lógica em JS</span><span class="text-xs text-emerald-400">Artigo</span></div><div class="space-y-3"><div class="h-2 w-3/4 rounded-full bg-cyan-400"></div><div class="h-2 w-11/12 rounded-full bg-blue-500/80"></div><div class="h-2 w-1/2 rounded-full bg-violet-400/80"></div><div class="h-2 w-2/3 rounded-full bg-emerald-400/70"></div></div></div>
                <div data-parallax data-depth="-4" class="mt-auto rounded-2xl bg-white p-4 text-slate-950 shadow-xl transition-transform duration-200"><p class="text-xs font-bold uppercase tracking-widest text-slate-500">Comunidade</p><p class="mt-2 text-sm font-bold">Uma conversa pode mudar seu caminho.</p></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mx-auto mt-32 max-w-6xl"><div class="grid gap-8 md:grid-cols-3">
        <article class="rounded-3xl border border-slate-700 bg-slate-800/40 p-8 backdrop-blur-lg transition-all duration-500 hover:-translate-y-4 hover:shadow-[0_0_40px_rgba(52,211,153,0.2)]"><p class="text-5xl font-black text-emerald-400">14% ao ano</p><p class="mt-4 text-slate-300">Crescimento do e-learning global</p></article>
        <article class="rounded-3xl border border-slate-700 bg-slate-800/40 p-8 backdrop-blur-lg transition-all duration-500 hover:-translate-y-4 hover:shadow-[0_0_40px_rgba(52,211,153,0.2)]"><p class="text-5xl font-black text-blue-400">Top 1</p><p class="mt-4 text-slate-300">Brasil é o maior mercado de educação digital da América Latina</p></article>
        <article class="rounded-3xl border border-slate-700 bg-slate-800/40 p-8 backdrop-blur-lg transition-all duration-500 hover:-translate-y-4 hover:shadow-[0_0_40px_rgba(52,211,153,0.2)]"><p class="text-5xl font-black text-cyan-400">+70%</p><p class="mt-4 text-slate-300">Dos brasileiros buscam novas habilidades online</p></article>
      </div></div>
      <section class="my-24 w-full border-y border-slate-800 bg-gradient-to-b from-slate-900 to-slate-950 py-24"><div class="container mx-auto flex max-w-4xl flex-col items-center px-6 text-center"><div class="mb-6 flex items-center gap-4"><div class="h-[1px] w-8 bg-blue-500"></div><span class="text-sm font-bold uppercase tracking-widest text-blue-400">Sobre Nós</span><div class="h-[1px] w-8 bg-blue-500"></div></div><h2 class="mb-10 text-4xl font-extrabold leading-tight text-white md:text-5xl">Construindo o ponto de encontro para o futuro da educação digital.</h2><p class="mb-6 text-lg leading-relaxed text-slate-400 md:text-xl">O HACD-Hub nasceu com um propósito claro: democratizar o acesso ao conhecimento e criar um ecossistema colaborativo. Nossa plataforma constrói pontes entre mentes curiosas que desejam aprender e especialistas que têm paixão por ensinar.</p><p class="mb-6 text-lg leading-relaxed text-slate-400 md:text-xl">Acreditamos que a verdadeira inovação acontece em comunidade. Estamos dando nossos primeiros passos para construir um ambiente seguro, prático e transformador, onde cada conexão gera um novo impacto.</p></div></section>
      <div class="mt-24 grid gap-8 md:grid-cols-2"><article class="rounded-3xl border border-slate-700 bg-slate-800/40 p-8 text-center backdrop-blur-lg"><h2 class="text-3xl font-bold text-white">Você é aluno?</h2><button data-page="cadastro" data-tipo="aluno" class="mt-8 rounded-full bg-blue-600 px-10 py-4 font-bold text-white shadow-[0_0_20px_rgba(37,99,235,0.5)] transition-transform duration-300 hover:scale-110 hover:bg-blue-500">Venha aprender com a gente</button></article><article class="rounded-3xl border border-slate-700 bg-slate-800/40 p-8 text-center backdrop-blur-lg"><h2 class="text-3xl font-bold text-white">Você é professor ou especialista?</h2><button data-page="cadastro" data-tipo="professor" class="mt-8 rounded-full bg-emerald-600 px-10 py-4 font-bold text-white shadow-[0_0_20px_rgba(16,185,129,0.5)] transition-transform duration-300 hover:scale-110 hover:bg-emerald-500">Venha ensinar com a gente</button></article></div>
      <section class="mx-auto mt-32 max-w-6xl border-t border-slate-800 py-24"><div class="grid gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div class="lg:sticky lg:top-32"><div class="mb-6 flex items-center gap-4"><div class="h-px w-8 bg-cyan-400"></div><span class="text-sm font-bold uppercase tracking-[0.24em] text-cyan-400">Dúvidas frequentes</span></div><h2 class="max-w-md text-4xl font-extrabold leading-tight text-white md:text-5xl">Tudo começa com uma boa pergunta.</h2><p class="mt-6 max-w-md text-lg leading-8 text-slate-400">Conheça a ideia por trás do HACD-Hub e veja como alunos e professores podem construir uma jornada de aprendizado em conjunto.</p></div><div class="space-y-4">${[
        ['Como surgiu o HACD-Hub?', 'O HACD-Hub nasceu de um projeto entre amigos que perceberam o crescimento do aprendizado digital e a importância de tornar esse caminho mais próximo, humano e colaborativo.'],
        ['O que posso encontrar por aqui?', 'Você encontra artigos publicados por professores, trilhas para explorar diferentes áreas e pessoas dispostas a compartilhar conhecimento por meio de mentorias.'],
        ['Como funciona para o aluno?', 'Depois do cadastro, o aluno informa sua área de interesse e passa a ver conteúdos e professores relacionados ao tema.'],
        ['Como funciona para o professor?', 'O professor escolhe sua especialidade, publica artigos e visualiza alunos que demonstraram interesse na mesma área.'],
        ['Preciso pagar para participar?', 'O cadastro na plataforma é gratuito. O HACD-Hub foi pensado para aproximar pessoas e facilitar o primeiro passo de quem quer aprender ou ensinar.']
      ].map(([pergunta, resposta], index) => `<details class="group rounded-2xl border border-slate-700 bg-slate-800/45 p-6 backdrop-blur-md transition hover:border-cyan-400/60" ${index === 0 ? 'open' : ''}><summary class="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-bold text-white">${pergunta}<span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-slate-600 text-xl font-normal text-cyan-400 transition group-open:rotate-45">+</span></summary><p class="mt-5 border-t border-slate-700 pt-5 leading-7 text-slate-400">${resposta}</p></details>`).join('')}</div></div></section>
    </section>`;
}
